version: '3'

services:
  orchestrator-service:
    build:
      context: ./orchestrator-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - product-service
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8081/

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"