server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:sqlite:backend/order-service/database/order.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect